name: GitHub Pages Deployment

on:
  push:
    branches:
      - main   # Build and deploy whenever main is updated

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files --non-interactive

      # 4. Build the web app
      - name: Build app
        run: yarn build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
